version: "3.9"

services:
  db:
    build: ./utils
    environment:
      POSTGRES_DB: vueapp
      POSTGRES_USER: vueUser
      POSTGRES_PASSWORD: p0stgressPassword!
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  django_app:
      build: ./django_app
      command:
          - bash
          - -c
          - |
            python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py makemigrations &&
            python manage.py create_custom_superuser &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:2550
      volumes:
        - ./django_app:/app
      ports:
        - "2550:2550"
      depends_on:
        - db
      environment:
        DJANGO_DB_ENGINE: django.db.backends.postgresql
        DJANGO_DB_NAME: vueapp
        DJANGO_DB_USER: vueUser
        DJANGO_DB_PASSWORD: p0stgressPassword!
        DJANGO_DB_HOST: db
        DJANGO_DB_PORT: 5432
        DJANGO_SECRET_KEY: notasecret
        DJANGO_SUPERUSER_EMAIL: admin@example.com
        DJANGO_SUPERUSER_PASSWORD: admin

  vue_app:
    build: ./vue_app
    command: yarn serve
    volumes:
      - ./vue_app:/app
    ports:
      - "8081:8081"
    depends_on:
      - django_app

volumes:
  postgres_data:
